# This file was generated by GoReleaser. DO NOT EDIT.
cask "simplecli" do
  name "simplecli"
  desc "A simple CLI tool to test automated deployments"
  homepage "https://hithub.com/jgrecu"
  version "1.0.3-beta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "simplecli"

  on_macos do
    on_intel do
      url "https://github.com/jgrecu/simplecli/releases/download/v#{version}/simplecli_MacOS_x86_64.tar.gz"
      sha256 "4db542c8b16dddbb3965daa00f71f99bfee861be38b3e9968c3ba0b1c2e95a17"
    end
    on_arm do
      url "https://github.com/jgrecu/simplecli/releases/download/v#{version}/simplecli_MacOS_arm64.tar.gz"
      sha256 "03fc99a848b48f22f8b4f9e8df74c1b215cd828434629417814c180554e50a75"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jgrecu/simplecli/releases/download/v#{version}/simplecli_Linux_x86_64.tar.gz"
      sha256 "b63ad8d13fa9082918a2f7171497ad7bd648e78337e7b4c1f0c428b78540c130"
    end
    on_arm do
      url "https://github.com/jgrecu/simplecli/releases/download/v#{version}/simplecli_Linux_arm64.tar.gz"
      sha256 "07fbec81bf64010ceb7dbf6517df201a516a401a587a08cc5ae3cc2057bd43e1"
    end
  end

  # No zap stanza required
end
